services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - t2
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: tws_db
    ports:
      - "3306:3306"

  flaskapp:
    image: siddhantkudal/python-two-tier:latest
    container_name: flask
    networks:
      - t2
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: tws_db
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    restart: always


volumes:
  my_db:
networks:
  t2:

